### ISSUE TITLE
stderr: fatal: unable to access The requested URL returned error: 500

### ISSUE THREAD

**Issue by SteveKennedy** [jenkinsci/azure-app-service-plugin#22]
It seems like the plugin successfully clones our .git on Azure, but then fails later.

Every successful call hits: https://mabeappswin.scm.azurewebsites.net:443/mabeappswin.git. 

The failure has this trailing slash: https://mabeappswin.scm.azurewebsites.net:443/mabeappswin.git/

Any help would be appreciated.

```
Starting Azure Web App Deployment
Cloning repository https://mabeappswin.scm.azurewebsites.net:443/mabeappswin.git
 > git init /var/lib/jenkins/workspace/mabeapps.azurewebsites.net/.azure-deploy # timeout=10
Fetching upstream changes from https://mabeappswin.scm.azurewebsites.net:443/mabeappswin.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://mabeappswin.scm.azurewebsites.net:443/mabeappswin.git +refs/heads/*:refs/remotes/origin/*
ERROR: Build step failed with exception
hudson.plugins.git.GitException: Command "git fetch --tags --progress https://mabeappswin.scm.azurewebsites.net:443/mabeappswin.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://mabeappswin.scm.azurewebsites.net:443/mabeappswin.git/': The requested URL returned error: 500

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1996)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1715)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:405)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:614)
	at com.microsoft.jenkins.appservice.commands.GitDeployCommand.execute(GitDeployCommand.java:85)
```

**Comment by ArchangelSDY** [comment]
Have you tried to clone the repo manually using command line git command? Besides what is you git version?

**Comment by gavinfish** [comment]
Closing for no response for long time. Please feel free to reopen it.
